# spack-stack hash: 00fbc7a
# spack hash: e5274e9c2d
spack:
  concretizer:
    unify: when_possible
  view: false
  include:
  - site
  - common
  specs:
  - ecmwf-atlas
  - ecbuild
  - eckit
  - fckit
  - parallelio
  - netcdf-c
  - netcdf-fortran
  - netcdf-cxx4
  - parallel-netcdf
  - gptl
  - jedi-cmake
  - gsl-lite
  - udunits
  - nccmp
  - py-pycodestyle

  packages:
    all:
      prefer: ['%gcc']
    eckit:
      require: "@1.25.2" 
    fckit:
      require: "@0.11.0" 
    ecmwf-atlas:  
      require: "@0.36.0" 
